# Generated by Django 4.1.13 on 2024-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('cardiologist', 'Врач-кардиолог'), ('otolaryngologist', 'Врач-отоларинголог'), ('therapist', 'Врач-терапевт'), ('hospital_therapist', 'Врач-терапевт госпитального отделения'), ('manual_therapy', 'Врач мануальной терапии'), ('reflexologist_neurologist', 'Врач-рефлексотерапевт-невролог'), ('psychiatrist', 'Врач-психиатр'), ('psychiatrist_narcologist', 'Врач-психиатр-нарколог'), ('hematologist', 'Врач-гематолог'), ('rheumatologist', 'Врач-ревматолог'), ('ophthalmologist', 'Врач-офтальмолог'), ('urologist', 'Врач-уролог'), ('gynecologist', 'Врач-акушер-гинеколог'), ('dermatologist', 'Врач-дерматовенеролог'), ('diagnostics_doctor', 'Врач функциональной диагностики'), ('surgeon', 'Врач-хирург'), ('neurosurgeon', 'Врач-нейрохирург'), ('traumatologist', 'Врач-травматолог'), ('maxillofacial_surgeon', 'Врач-челюстно-лицевой хирург'), ('angiographer', 'Врач-ангиографист'), ('transfusiologist', 'Врач-трансфузиолог'), ('neonatologist', 'Врач-неонатолог'), ('cardiovascular_surgeon', 'Врач-сердечно-сосудистый хирург'), ('anesthesiologist', 'Врач-анестезиолог'), ('feldsher_commission', 'Фельдшер военно-врачебной комиссии'), ('nurse_commission', 'Медицинская сестра военно-врачебной комиссии'), ('nurse_surgical', 'Медицинская сестра хирургического отделения'), ('nurse_ent', 'Медицинская сестра отоларингологического отделения'), ('nurse_procedural', 'Медицинская сестра процедурного кабинета'), ('nurse_neurological', 'Медицинская сестра неврологического отделения'), ('nurse_dermatological', 'Медицинская сестра кожно-венерологического отделения'), ('nurse_dispensary', 'Медицинская сестра диспансерного отделения'), ('nurse_consultation', 'Медицинская сестра консультативного отделения'), ('nurse_hospital', 'Медицинская сестра палатная (постовая) госпитального отделения'), ('nurse_physiotherapy', 'Медицинская сестра физиотерапевтического отделения'), ('nurse_functional_diagnostics', 'Медицинская сестра отделения функциональной диагностики'), ('nurse_operating', 'Медицинская сестра операционного отделения'), ('nurse_urology', 'Медицинская сестра урологического отделения'), ('nurse_cardiology', 'Медицинская сестра кардиологического отделения'), ('nurse_neonatal', 'Медицинская сестра отделения реанимации новорожденных'), ('nurse_neonatal_pathology', 'Медицинская сестра отделения патологии новорожденных'), ('nurse_transfusion', 'Медицинская сестра отделения трансфузиологии'), ('radiology_technician', 'Рентгенолаборант'), ('medical_registrar', 'Медицинский регистратор'), ('orderly_surgical', 'Санитарка хирургического отделения'), ('orderly_ent', 'Санитарка отоларингологического отделения'), ('orderly_procedural', 'Санитарка процедурного кабинета'), ('orderly_neurological', 'Санитарка неврологического отделения'), ('orderly_consultation', 'Санитарка консультативного отделения'), ('orderly_dispensary', 'Санитарка диспансерного отделения'), ('orderly_hospital', 'Санитарка госпитального отделения'), ('orderly_operating', 'Санитарка операционного отделения')], max_length=50, verbose_name='Должность'),
        ),
    ]
