# Generated by Django 4.1.13 on 2024-12-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_profile_role'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('method', models.TextField(verbose_name='Метод лечения (например, "операция", "медикаментозная терапия")')),
                ('medication', models.TextField(verbose_name='Название препарата')),
                ('dosage', models.TextField(verbose_name='Дозировка')),
                ('notes', models.TextField()),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to='medical_records.medicalrecords')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('action_type', models.CharField(max_length=20, verbose_name='Тип действия')),
                ('nurse', models.ForeignKey(blank=True, limit_choices_to={'role__startswith': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_schedule', to='account.profile', verbose_name='Медсестра')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_record_shech', to='treatments.treatments')),
            ],
        ),
    ]
