# Generated by Django 4.1.13 on 2024-12-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=20, verbose_name='пол')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(choices=[('abay', 'Абайская область'), ('akmola', 'Акмолинская область'), ('aktobe', 'Актюбинская область'), ('almaty_region', 'Алматинская область'), ('atyrau', 'Атырауская область'), ('east_kazakhstan', 'Восточно-Казахстанская область'), ('zhambyl', 'Жамбылская область'), ('zhetisu', 'Жетысуская область'), ('west_kazakhstan', 'Западно-Казахстанская область'), ('karaganda', 'Карагандинская область'), ('kostanay', 'Костанайская область'), ('kyzylorda', 'Кызылординская область'), ('mangystau', 'Мангистауская область'), ('turkistan', 'Туркестанская область'), ('north_kazakhstan', 'Северо-Казахстанская область'), ('ulytau', 'Улытауская область'), ('astana', 'Астана (город республиканского значения)'), ('almaty', 'Алматы (город республиканского значения)'), ('shymkent', 'Шымкент (город республиканского значения)')], max_length=50, verbose_name='Регион проживания')),
                ('iin', models.CharField(blank=True, max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('surgery', 'Хирургическое отделение'), ('urology', 'Урологическое отделение'), ('ent', 'Отоларингологическое отделение'), ('maxillofacial', 'Отделение челюстно–лицевой хирургии'), ('traumatology', 'Травматологическое отделение'), ('neurosurgery', 'Нейрохирургическое отделение'), ('ophthalmology', 'Офтальмологическое отделение'), ('anesthesia', 'Отделение анестезиологии и реанимации'), ('operating_room', 'Операционное отделение'), ('angiography', 'Отделение рентген-ангио-хирургических методов диагностики и лечения'), ('transfusion', 'Отделение трансфузиологии (переливания крови)'), ('maternity', 'Родильное отделение'), ('neonatal_reanimation', 'Отделение реанимации новорожденных'), ('neonatal_pathology', 'Отделение патологии новорожденных и выхаживания недоношенных'), ('cardiology', 'Кардиологическое отделение'), ('cardiovascular_surgery', 'Отделение сердечно-сосудистой хирургии'), ('neurology', 'Неврологическое отделение с инсультным центром'), ('diagnostic_center', 'Клинико-диагностический центр'), ('pathology', 'Патологоанатомическое отделение'), ('gynecology', 'Гинекологическое отделение'), ('rehabilitation', 'Отделение восстановительного лечения и медицинской реабилитации')], max_length=50, verbose_name='отделение пациента')),
            ],
        ),
    ]
