# Generated by Django 4.1.13 on 2024-12-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='тип анализа')),
                ('date', models.DateField(verbose_name='Дата анализа')),
                ('result', models.FileField(upload_to='diagnostics_results/', verbose_name='Результат анализа')),
            ],
        ),
    ]
