# Generated by Django 4.1.13 on 2024-12-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='medical_records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics_records', to='medical_records.medicalrecords'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics_patients', to='patients.patients'),
        ),
    ]
