# Generated by Django 4.1.13 on 2024-12-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medic', '0001_initial'),
        ('account', '0003_alter_profile_role'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordsPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.IntegerField(verbose_name='Тип крови')),
                ('rh_factor', models.CharField(max_length=25, verbose_name='Резус фактор пациента')),
                ('chronic_diseases', models.TextField(verbose_name='Хронические болезни пациента')),
                ('allergies', models.TextField(verbose_name='Аллергии')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_of_patient', to='patients.patients')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_for_doctor', models.TextField(verbose_name='Запись для врачей')),
                ('notes_for_nurses', models.TextField(verbose_name='Запись для медсестер')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role__startswith': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record_doc', to='account.profile', verbose_name='Лечащий врач')),
                ('hospitalizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='medic.hospitalizations')),
            ],
        ),
    ]
